---
- include_tasks: 1_1_create_instance.yml

- block:
    - name: Get API Pod details
      k8s_info:
        namespace: '{{ namespace }}'
        kind: Pod
        label_selectors:
          - app.kubernetes.io/name = ansibleaiconnect-sample
      register: aiconnect_api_pod

    - name: Get API Service details
      k8s_info:
        namespace: '{{ namespace }}'
        kind: Service
        label_selectors:
          - app.kubernetes.io/name = ansibleaiconnect-sample
      register: aiconnect_api_service

    - name: Get Health Check
      uri:
        url: 'http://{{ service_host_ip }}:{{ service_host_port }}/check/'
        return_content: true
      vars:
        service_host_ip: '{{ aiconnect_api_pod.resources[0].status.hostIP }}'
        service_host_port: '{{ aiconnect_api_service.resources[0].spec.ports[0].nodePort }}'
      register: service_host_response

    - name: Assert Health Check response
      assert:
        that:
        - service_host_response.status == 200
        - service_host_response.json.status == 'ok'
        fail_msg: /check endpoint did not return expected response. Expected HTTP200, OK.
