---
- block:
    - name: Get API Pod details
      kubernetes.core.k8s_info:
        namespace: '{{ namespace }}'
        kind: Pod
        label_selectors:
          - app.kubernetes.io/name = ansibleaiconnect-sample
      register: aiconnect_api_pod

    - name: Get API Service details
      kubernetes.core.k8s_info:
        namespace: '{{ namespace }}'
        kind: Service
        label_selectors:
          - app.kubernetes.io/name = ansibleaiconnect-sample
      register: aiconnect_api_service

    - name: Get original model_id
      ansible.builtin.uri:
        url: 'http://{{ service_host_ip }}:{{ service_host_port }}/check/status/'
        return_content: true
      vars:
        service_host_ip: '{{ aiconnect_api_pod.resources[0].status.hostIP }}'
        service_host_port: '{{ aiconnect_api_service.resources[0].spec.ports[0].nodePort }}'
      register: service_host_response

    - name: Assert original model_id response
      ansible.builtin.assert:
        that:
          - service_host_response.status == 200
          - service_host_response.json.status == 'ok'
          - service_host_response.json.model_id== 'my-ai-model_id'
        fail_msg: /check/status did not return expected model_id. Expected 'my-ai-model_id'.

    - ansible.builtin.include_tasks: 2_1_update_model_config_secret.yml

    - name: Get updated model_id
      ansible.builtin.uri:
        url: 'http://{{ service_host_ip }}:{{ service_host_port }}/check/status/'
        return_content: true
      vars:
        service_host_ip: '{{ aiconnect_api_pod.resources[0].status.hostIP }}'
        service_host_port: '{{ aiconnect_api_service.resources[0].spec.ports[0].nodePort }}'
      register: updated_service_host_response

    - name: Assert updated model_id response
      ansible.builtin.assert:
        that:
        - updated_service_host_response.status == 200
        - updated_service_host_response.json.status == 'ok'
        - updated_service_host_response.json.model_id == 'updated__my-ai-model_id'
        fail_msg: /check/status did not return expected model_id. Expected 'updated__my-ai-model_id'.
